import type { Product, Customer, Order } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Áo Thun Nam Cổ Tròn",
    description: "Áo thun nam chất liệu cotton 100%, thoáng mát, dễ giặt",
    price: 199000,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    category: "Áo",
    stock: 50,
    sku: "ATN-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Quần Jeans Nam",
    description: "Quần jeans nam form slim, chất liệu denim cao cấp",
    price: 599000,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
    category: "Quần",
    stock: 30,
    sku: "QJN-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Giày Sneaker",
    description: "Giày sneaker unisex, đế cao su chống trượt",
    price: 899000,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
    category: "Giày",
    stock: 25,
    sku: "GS-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Áo Sơ Mi Nam",
    description: "Áo sơ mi nam công sở, form fit, chất liệu cotton",
    price: 399000,
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500&h=500&fit=crop",
    category: "Áo",
    stock: 40,
    sku: "ASM-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Túi Xách Da",
    description: "Túi xách da thật, thiết kế sang trọng, phù hợp công sở",
    price: 1299000,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
    category: "Phụ kiện",
    stock: 15,
    sku: "TXD-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Đồng Hồ Nam",
    description: "Đồng hồ nam dây da, mặt kính sapphire chống xước",
    price: 2499000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
    category: "Phụ kiện",
    stock: 20,
    sku: "DHN-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    phone: "0901234567",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    totalOrders: 5,
    totalSpent: 2500000,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Trần Thị B",
    email: "tranthib@example.com",
    phone: "0907654321",
    address: "456 Đường XYZ, Quận 2, TP.HCM",
    totalOrders: 3,
    totalSpent: 1800000,
    createdAt: new Date().toISOString(),
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    customerId: "1",
    customerName: "Nguyễn Văn A",
    customerEmail: "nguyenvana@example.com",
    customerPhone: "0901234567",
    customerAddress: "123 Đường ABC, Quận 1, TP.HCM",
    items: [
      {
        product: mockProducts[0],
        quantity: 2,
      },
      {
        product: mockProducts[1],
        quantity: 1,
      },
    ],
    total: 997000,
    status: "pending",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "ORD-002",
    customerId: "2",
    customerName: "Trần Thị B",
    customerEmail: "tranthib@example.com",
    customerPhone: "0907654321",
    customerAddress: "456 Đường XYZ, Quận 2, TP.HCM",
    items: [
      {
        product: mockProducts[2],
        quantity: 1,
      },
    ],
    total: 899000,
    status: "shipped",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "ORD-003",
    customerId: "3",
    customerName: "Lê Văn C",
    customerEmail: "levanc@example.com",
    customerPhone: "0912345678",
    customerAddress: "789 Đường DEF, Quận 3, TP.HCM",
    items: [
      {
        product: mockProducts[3],
        quantity: 3,
      },
      {
        product: mockProducts[4],
        quantity: 1,
      },
    ],
    total: 2097000,
    status: "confirmed",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "ORD-004",
    customerId: "4",
    customerName: "Phạm Thị D",
    customerEmail: "phamthid@example.com",
    customerPhone: "0923456789",
    customerAddress: "321 Đường GHI, Quận 4, TP.HCM",
    items: [
      {
        product: mockProducts[5],
        quantity: 1,
      },
      {
        product: mockProducts[0],
        quantity: 1,
      },
    ],
    total: 2698000,
    status: "processing",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "ORD-005",
    customerId: "5",
    customerName: "Hoàng Văn E",
    customerEmail: "hoangvane@example.com",
    customerPhone: "0934567890",
    customerAddress: "654 Đường JKL, Quận 5, TP.HCM",
    items: [
      {
        product: mockProducts[1],
        quantity: 2,
      },
      {
        product: mockProducts[2],
        quantity: 1,
      },
    ],
    total: 2097000,
    status: "delivered",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "ORD-006",
    customerId: "6",
    customerName: "Võ Thị F",
    customerEmail: "vothif@example.com",
    customerPhone: "0945678901",
    customerAddress: "987 Đường MNO, Quận 6, TP.HCM",
    items: [
      {
        product: mockProducts[4],
        quantity: 2,
      },
    ],
    total: 2598000,
    status: "pending",
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    updatedAt: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: "ORD-007",
    customerId: "7",
    customerName: "Đặng Văn G",
    customerEmail: "dangvang@example.com",
    customerPhone: "0956789012",
    customerAddress: "147 Đường PQR, Quận 7, TP.HCM",
    items: [
      {
        product: mockProducts[3],
        quantity: 5,
      },
      {
        product: mockProducts[0],
        quantity: 2,
      },
    ],
    total: 2393000,
    status: "shipped",
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: "ORD-008",
    customerId: "8",
    customerName: "Bùi Thị H",
    customerEmail: "buithih@example.com",
    customerPhone: "0967890123",
    customerAddress: "258 Đường STU, Quận 8, TP.HCM",
    items: [
      {
        product: mockProducts[5],
        quantity: 1,
      },
    ],
    total: 2499000,
    status: "cancelled",
    createdAt: new Date(Date.now() - 691200000).toISOString(),
    updatedAt: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: "ORD-009",
    customerId: "9",
    customerName: "Trương Văn I",
    customerEmail: "truongvani@example.com",
    customerPhone: "0978901234",
    customerAddress: "369 Đường VWX, Quận 9, TP.HCM",
    items: [
      {
        product: mockProducts[2],
        quantity: 3,
      },
      {
        product: mockProducts[1],
        quantity: 1,
      },
    ],
    total: 3296000,
    status: "delivered",
    createdAt: new Date(Date.now() - 777600000).toISOString(),
    updatedAt: new Date(Date.now() - 691200000).toISOString(),
  },
  {
    id: "ORD-010",
    customerId: "10",
    customerName: "Ngô Thị K",
    customerEmail: "ngothik@example.com",
    customerPhone: "0989012345",
    customerAddress: "741 Đường YZ, Quận 10, TP.HCM",
    items: [
      {
        product: mockProducts[4],
        quantity: 1,
      },
      {
        product: mockProducts[3],
        quantity: 2,
      },
      {
        product: mockProducts[0],
        quantity: 1,
      },
    ],
    total: 3096000,
    status: "processing",
    createdAt: new Date(Date.now() - 864000000).toISOString(),
    updatedAt: new Date(Date.now() - 777600000).toISOString(),
  },
  {
    id: "ORD-011",
    customerId: "11",
    customerName: "Lý Văn L",
    customerEmail: "lyvanl@example.com",
    customerPhone: "0990123456",
    customerAddress: "852 Đường Alpha, Quận 11, TP.HCM",
    items: [
      {
        product: mockProducts[1],
        quantity: 4,
      },
    ],
    total: 2396000,
    status: "confirmed",
    createdAt: new Date(Date.now() - 950400000).toISOString(),
    updatedAt: new Date(Date.now() - 864000000).toISOString(),
  },
  {
    id: "ORD-012",
    customerId: "12",
    customerName: "Đỗ Thị M",
    customerEmail: "dothim@example.com",
    customerPhone: "0901123456",
    customerAddress: "963 Đường Beta, Quận 12, TP.HCM",
    items: [
      {
        product: mockProducts[5],
        quantity: 2,
      },
      {
        product: mockProducts[2],
        quantity: 1,
      },
    ],
    total: 4297000,
    status: "shipped",
    createdAt: new Date(Date.now() - 1036800000).toISOString(),
    updatedAt: new Date(Date.now() - 950400000).toISOString(),
  },
];

